isbn: '9784763136091'
title: '「いまの説明、わかりやすいね！」と言われるコツ'
authors: ['浅田すぐる']
publisherName: 'サンマーク出版'
publishedDate: 2017-04-05
itemPrice: 1430
pageCount: 208
categories: ['自己啓発']
finishDate: 2023-09-06
buyUrl: 'https://hb.afl.rakuten.co.jp/hgc/g00q072a.84u5t82d.g00q072a.84u5u12d/?pc=https%3A%2F%2Fbooks.rakuten.co.jp%2Frb%2F14729664%2F'

chapters:
  - about
