isbn: '9784798171548'
title: '「技術書」の読書術 達人が教える選び方・読み方・情報発信&共有のコツとテクニック'
authors: ['IPUSIRON', '増井 敏克']
publisherName: '翔泳社'
publishedDate: 2022-11-04
itemPrice: 2200
pageCount: 272
categories: ['自己啓発']
finishDate: 2023-11-18
buyUrl: 'https://hb.afl.rakuten.co.jp/hgc/g00q072a.84u5t82d.g00q072a.84u5u12d/?pc=https%3A%2F%2Fbooks.rakuten.co.jp%2Frb%2F17277953%2F'

chapters:
  - about
