isbn: '9784798171548'
title: '「技術書」の読書術 達人が教える選び方・読み方・情報発信&共有のコツとテクニック'
authors: ['IPUSIRON', '増井 敏克']
publisherName: '翔泳社'
publishedDate: 2022-11-04
itemPrice: 2200
pageCount: 272
categories: ['読書術', '自己啓発']
finishDate: 2023-11-18
buyUrl: 'https://hb.afl.rakuten.co.jp/hgc/g00q072a.84u5t82d.g00q072a.84u5u12d/?pc=https%3A%2F%2Fbooks.rakuten.co.jp%2Frb%2F17277953%2F'

chapters:
  - how-to-choose-books-masui
  - how-to-choose-books-ipusiron
  - how-to-read-books-masui
  - how-to-read-books-ipusiron
  - how-to-output_masui
  - how-to-output-ipusiron

records:
  - date: 2023-11-15
    pages: [1, 80]
  - date: 2023-11-16
    pages: [81, 132]
  - date: 2023-11-17
    pages: [133, 220]
  - date: 2023-11-18
    pages: [221, 262]
