isbn: '9784798165943'
title: '深層学習教科書 ディープラーニング G検定（ジェネラリスト）公式テキスト 第2版'
authors:
  [
    '猪狩 宇司',
    '今井 翔太',
    '江間 有沙',
    '岡田 陽介',
    '工藤 郁子',
    '巣籠 悠輔',
    '瀬谷 啓介',
    '徳田 有美子',
    '中澤 敏明',
    '藤本 敬介',
    '松井 孝之',
    '松尾 豊',
    '松嶋 達也',
    '山下 隆義',
  ]
publisherName: '翔泳社'
publishedDate: 2021-04-27
itemPrice: 3080
pageCount: 404
categories: ['DNN', '資格試験']
finishDate:
buyUrl: 'https://hb.afl.rakuten.co.jp/hgc/g00q072a.84u5t82d.g00q072a.84u5u12d/?pc=https%3A%2F%2Fbooks.rakuten.co.jp%2Frb%2F16665998%2F'

chapters:
  - about
