isbn: ''
title: ''
authors: ['']
publisherName: ''
publishedDate: 1970-01-01
itemPrice: 3000
pageCount: 100
categories: ['']
finishDate: 1970-01-01
buyUrl: ''

chapters:
  - note

records:
  - date: 1970-01-01
    pages: [1, 30]
